version: "2017-09-20"
pipeline:
- id: build
  overlay: ci/golang
  type: script
  cache:
    paths:
    - /go/pkg/mod
    - ~/.cache/go-build
  commands:
  - desc: test & check
    cmd: |
      make test
  - desc: build
    cmd: |
      make build.docker
  - desc: push
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        IMAGE=registry-write.opensource.zalan.do/teapot/kube-aws-iam-controller
        VERSION=$(git describe --tags --always --dirty)
      else
        IMAGE=registry-write.opensource.zalan.do/teapot/kube-aws-iam-controller-test
        VERSION="${CDP_BUILD_VERSION}"
      fi
      IMAGE="${IMAGE}" VERSION="${VERSION}" make build.push
  - desc: build-and-push-ecr
    cmd: |
      if [[ $CDP_TARGET_BRANCH == master && ! $CDP_PULL_REQUEST_NUMBER ]]; then
        IMAGE=container-registry-test.zalando.net/teapot/kube-aws-iam-controller
        VERSION=$(git describe --tags --always --dirty)
      else
        IMAGE=container-registry-test.zalando.net/teapot/kube-aws-iam-controller-test
        VERSION="${CDP_BUILD_VERSION}"
      fi
      IMAGE="${IMAGE}" VERSION="${VERSION}" make build.push.manifest
