/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	zalandoorgv1 "github.com/zalando-incubator/kube-aws-iam-controller/pkg/apis/zalando.org/v1"
	scheme "github.com/zalando-incubator/kube-aws-iam-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AWSIAMRolesGetter has a method to return a AWSIAMRoleInterface.
// A group's client should implement this interface.
type AWSIAMRolesGetter interface {
	AWSIAMRoles(namespace string) AWSIAMRoleInterface
}

// AWSIAMRoleInterface has methods to work with AWSIAMRole resources.
type AWSIAMRoleInterface interface {
	Create(ctx context.Context, aWSIAMRole *zalandoorgv1.AWSIAMRole, opts metav1.CreateOptions) (*zalandoorgv1.AWSIAMRole, error)
	Update(ctx context.Context, aWSIAMRole *zalandoorgv1.AWSIAMRole, opts metav1.UpdateOptions) (*zalandoorgv1.AWSIAMRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aWSIAMRole *zalandoorgv1.AWSIAMRole, opts metav1.UpdateOptions) (*zalandoorgv1.AWSIAMRole, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*zalandoorgv1.AWSIAMRole, error)
	List(ctx context.Context, opts metav1.ListOptions) (*zalandoorgv1.AWSIAMRoleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *zalandoorgv1.AWSIAMRole, err error)
	AWSIAMRoleExpansion
}

// aWSIAMRoles implements AWSIAMRoleInterface
type aWSIAMRoles struct {
	*gentype.ClientWithList[*zalandoorgv1.AWSIAMRole, *zalandoorgv1.AWSIAMRoleList]
}

// newAWSIAMRoles returns a AWSIAMRoles
func newAWSIAMRoles(c *ZalandoV1Client, namespace string) *aWSIAMRoles {
	return &aWSIAMRoles{
		gentype.NewClientWithList[*zalandoorgv1.AWSIAMRole, *zalandoorgv1.AWSIAMRoleList](
			"awsiamroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *zalandoorgv1.AWSIAMRole { return &zalandoorgv1.AWSIAMRole{} },
			func() *zalandoorgv1.AWSIAMRoleList { return &zalandoorgv1.AWSIAMRoleList{} },
		),
	}
}
