/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/zalando-incubator/kube-aws-iam-controller/pkg/apis/zalando.org/v1"
	scheme "github.com/zalando-incubator/kube-aws-iam-controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AWSIAMRolesGetter has a method to return a AWSIAMRoleInterface.
// A group's client should implement this interface.
type AWSIAMRolesGetter interface {
	AWSIAMRoles(namespace string) AWSIAMRoleInterface
}

// AWSIAMRoleInterface has methods to work with AWSIAMRole resources.
type AWSIAMRoleInterface interface {
	Create(ctx context.Context, aWSIAMRole *v1.AWSIAMRole, opts metav1.CreateOptions) (*v1.AWSIAMRole, error)
	Update(ctx context.Context, aWSIAMRole *v1.AWSIAMRole, opts metav1.UpdateOptions) (*v1.AWSIAMRole, error)
	UpdateStatus(ctx context.Context, aWSIAMRole *v1.AWSIAMRole, opts metav1.UpdateOptions) (*v1.AWSIAMRole, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AWSIAMRole, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AWSIAMRoleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AWSIAMRole, err error)
	AWSIAMRoleExpansion
}

// aWSIAMRoles implements AWSIAMRoleInterface
type aWSIAMRoles struct {
	client rest.Interface
	ns     string
}

// newAWSIAMRoles returns a AWSIAMRoles
func newAWSIAMRoles(c *ZalandoV1Client, namespace string) *aWSIAMRoles {
	return &aWSIAMRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the aWSIAMRole, and returns the corresponding aWSIAMRole object, and an error if there is any.
func (c *aWSIAMRoles) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AWSIAMRole, err error) {
	result = &v1.AWSIAMRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsiamroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AWSIAMRoles that match those selectors.
func (c *aWSIAMRoles) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AWSIAMRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AWSIAMRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awsiamroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested aWSIAMRoles.
func (c *aWSIAMRoles) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awsiamroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a aWSIAMRole and creates it.  Returns the server's representation of the aWSIAMRole, and an error, if there is any.
func (c *aWSIAMRoles) Create(ctx context.Context, aWSIAMRole *v1.AWSIAMRole, opts metav1.CreateOptions) (result *v1.AWSIAMRole, err error) {
	result = &v1.AWSIAMRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awsiamroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aWSIAMRole).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a aWSIAMRole and updates it. Returns the server's representation of the aWSIAMRole, and an error, if there is any.
func (c *aWSIAMRoles) Update(ctx context.Context, aWSIAMRole *v1.AWSIAMRole, opts metav1.UpdateOptions) (result *v1.AWSIAMRole, err error) {
	result = &v1.AWSIAMRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsiamroles").
		Name(aWSIAMRole.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aWSIAMRole).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *aWSIAMRoles) UpdateStatus(ctx context.Context, aWSIAMRole *v1.AWSIAMRole, opts metav1.UpdateOptions) (result *v1.AWSIAMRole, err error) {
	result = &v1.AWSIAMRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awsiamroles").
		Name(aWSIAMRole.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(aWSIAMRole).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the aWSIAMRole and deletes it. Returns an error if one occurs.
func (c *aWSIAMRoles) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsiamroles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *aWSIAMRoles) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awsiamroles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched aWSIAMRole.
func (c *aWSIAMRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AWSIAMRole, err error) {
	result = &v1.AWSIAMRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awsiamroles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
